[config.wallpaper]
command = "awww"
arguments = [
  "img",
  "--transition-type",
  "center",
  "--transition-fps",
  "60",
  "--transition-step",
  "255",
]
set = true

# Rofi
[templates.rofi]
input_path = '~/.config/matugen/templates/rofi-colors.rasi'
output_path = '~/.config/rofi/matugen/matugen-rofi.rasi'

# Waybar
[templates.waybar]
input_path = '~/.config/matugen/templates/colors.css'
output_path = '~/.config/waybar/colors/colors.css'
post_hook = 'pkill -SIGUSR2 waybar'

# Hyprlock
[templates.hyprlock]
input_path = '~/.config/matugen/templates/matugen-hyprlock.conf'
output_path = '~/.config/hypr/hyprlock/matugen/matugen-hyprlock.conf'

# Swaync
[templates.swaync]
input_path = '~/.config/matugen/templates/matugen-swaync.css'
output_path = '~/.config/swaync/matugen/matugen-swaync.css'
post_hook = 'swaync-client -rs'

# Gtk3
[templates.gtk3]
input_path = '~/.config/matugen/templates/matugen-gtk.css'
output_path = '~/.config/gtk-3.0/gtk.css'

# Gtk4
[templates.gtk4]
input_path = '~/.config/matugen/templates/matugen-gtk.css'
output_path = '~/.config/gtk-4.0/gtk.css'

# # Qt5
# [templates.qt5]
# input_path = '~/.config/matugen/templates/qtct-colors.conf'
# output_path = '~/.config/qt5ct/colors/matugen-qt5ct.conf'
#
# # Qt6
# [templates.qt6]
# input_path = '~/.config/matugen/templates/qtct-colors.conf'
# output_path = '~/.config/qt6ct/colors/matugen-qt6ct.conf'

# Pywalfox
# [templates.pywalfox]
# input_path = '~/.config/matugen/templates/pywalfox-colors.json'
# output_path = '~/.cache/wal/colors.json'
# post_hook = 'pywalfox update'
